######################################################################
##
## Filename: SEQ_DECOMPOSER_WITH_ADC.udo
## Created on: Sat Apr 14 06:31:31 PM India Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
