######################################################################
##
## Filename: SEQ_DECOMPOSER.udo
## Created on: Thu Mar 08 11:53:37 PM India Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
