######################################################################
##
## Filename: test_DC_offset_removal.udo
## Created on: Thu Apr 12 10:30:37 AM India Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
